### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by LankyBox01** [PigeonVideo/PigeonVideo.github.io#9]
discuss here.

**Comment by Readtt** [comment]
Can you add me back?

**Comment by Readtt** [comment]
Oh ok thx

**Comment by Readtt** [comment]
hmmm

**Comment by Readtt** [comment]
What should I do?

**Comment by LankyBox01** [comment]
I don't know

**Comment by LankyBox01** [comment]
Go ahead and write some code, or could you do a ToU?

**Comment by Readtt** [comment]
Wots a ToU

**Comment by LankyBox01** [comment]
Terms of use, lie how youre supposed to use the site and how not to

**Comment by Readtt** [comment]
Oh...

**Comment by Readtt** [comment]
Pretty sure thats ToS

**Comment by LankyBox01** [comment]
ToU = Terms of Use
ToS = Terms of Service
TaC = Terms and Conditions

Get it right.

**Comment by Readtt** [comment]
xdxdxdxdxdxdxdxdxdxxd

**Comment by LankyBox01** [comment]
Pretty embarassing, right?

**Comment by LankyBox01** [comment]
Anyways, go write one

**Comment by Readtt** [comment]
Alright.

**Comment by Readtt** [comment]
Can I just put it in a .md file?

**Comment by LankyBox01** [comment]
Yee that's how it works

**Comment by LankyBox01** [comment]
Add 2 sections:
Account Suspension
DMCA Takedowns

We'll add more later.

**Comment by Readtt** [comment]
This isn't going to be a po*n website, is it?

**Comment by Readtt** [comment]
What's the max file limit?

**Comment by Readtt** [comment]
16mb?

**Comment by LankyBox01** [comment]
I guess 16MB
And this is a website for kids, what is going trough your mind?

**Comment by Readtt** [comment]
lmao xd

**Comment by LankyBox01** [comment]
Any adult content is prohibited.

**Comment by LankyBox01** [comment]
There is a specialist that will come help us in a few minutes.

**Comment by Readtt** [comment]
![image](https://user-images.githubusercontent.com/35353525/94498962-75b85100-01c9-11eb-9e17-336a51cfcc06.png)

**Comment by Readtt** [comment]
Looking good so far I guess.

**Comment by LankyBox01** [comment]
Cool!

**Comment by Readtt** [comment]
![image](https://user-images.githubusercontent.com/35353525/94499171-fd9e5b00-01c9-11eb-9796-46f91c5f6472.png)

**Comment by Readtt** [comment]
We will have a reporting system, right?

**Comment by LankyBox01** [comment]
Yea.. if we have good coders

**Comment by Readtt** [comment]
xd

**Comment by LankyBox01** [comment]
The 1.1 is un-understandable, could you simplify it?

**Comment by Readtt** [comment]
We can do all of that in the end.

**Comment by Readtt** [comment]
For now I guess Ill actually write the TOU

**Comment by LankyBox01** [comment]
No, we must make sure everything is understandable to ensure no flaws in the community

**Comment by Readtt** [comment]
:p

**Comment by LankyBox01** [comment]
So?

**Comment by Readtt** [comment]
Ill check it with grammerly.

**Comment by LankyBox01** [comment]
Lol grammarly

**Comment by Readtt** [comment]
*Grammerly pro*

**Comment by LankyBox01** [comment]
*whatever just get to work*

**Comment by LankyBox01** [comment]
So what did you do till now?

**Comment by Readtt** [comment]
![image](https://user-images.githubusercontent.com/35353525/94499917-e3fe1300-01cb-11eb-91f4-135040c07022.png)

**Comment by Readtt** [comment]
Ima grammerly it now.

**Comment by garnetluvcookie** [comment]
yo

**Comment by LankyBox01** [comment]
Yo garnet. Make up some rules for a video-sharing website for kids

**Comment by Readtt** [comment]
@garnetluvcookie Nice pfp.

**Comment by LankyBox01** [comment]
Lol

**Comment by Readtt** [comment]
![image](https://user-images.githubusercontent.com/35353525/94500122-74d4ee80-01cc-11eb-87cc-4b75b2de88ff.png)

**Comment by Readtt** [comment]
Now DMCS Takedowns, Ill do that tmr. I have school so Ima go to bed.

**Comment by LankyBox01** [comment]
From where didja get that?

**Comment by LankyBox01** [comment]
Did you copy it online?

**Comment by Readtt** [comment]
`# TOU (Terms of Use)
___
##### SECTION 1: ACCOUNT SUSPENSIONS
###### 1.1. Pigeon Video has established an easily accessible means of allowing anyone to notify the availability of infringing, illegal, or adult content by reporting it on the Pigeon Video service.
###### 1.2. Suppose you notice any infringing, illegal and or adult content. In that case, you can report it to us at any time by contacting us via reporting the video from the video page directly or contacting us via the form on the homepage of the Pigeon Video website.
__
##### SECTION 2: PROHIBITED CONTENT POLICY
###### 2.1. Pigeon Video seeks to help provide users worldwide with a safe, respectful and friendly viewing environment. By banning the following prohibited content, we, at Pigeon Video, seek to protect the community and maintain a secure and happy user-base.

__

 ___Types of Prohibited Content___
 ___
a. __Sexually Explicit or Child Abuse Content__
b. __Harmful, Dangerous, Violent or Illegal Actions in Content__
c. __Hateful or Excessively Vulgar Speech in Content__
d. __Graphic, Violent or Repulsive Content__
e. __Threats, Harassment, and Personal Information in Content__
f. __Spam, Fake Engagement, Scam, Disinformation or Deceptive Content__
g. __Copyright-Infringing Content__

__
## DMCA Takedowns`

What I have so far. You guys can add to it.

**Comment by LankyBox01** [comment]
Did you take some of the texts from online?

**Comment by Readtt** [comment]
A bit.

**Comment by Readtt** [comment]
Didn't copy paste tho obviosuly

**Comment by LankyBox01** [comment]
From where?

**Comment by Readtt** [comment]
Just searched up random sites.

**Comment by LankyBox01** [comment]
Check ur history
Tell me the sites

**Comment by Readtt** [comment]
dailymotion 💯

**Comment by Readtt** [comment]
https://www.dailymotion.com/legal

**Comment by LankyBox01** [comment]
Thats it?

**Comment by Readtt** [comment]
yup.

**Comment by LankyBox01** [comment]
How much did you use

**Comment by LankyBox01** [comment]
It's important

**Comment by Readtt** [comment]
Bruh, I barely even wrote anything......

**Comment by garnetluvcookie** [comment]
> Yo garnet. Make up some rules for a video-sharing website for kids

got it but like rules rules or "yeeee be nice"

**Comment by Readtt** [comment]
I just took like "Types of Prohibited Content"

**Comment by LankyBox01** [comment]
Garnet
Rules. Rules. Try to be proffesional

**Comment by Readtt** [comment]
I can add some more tmr. For now cya.

**Comment by garnetluvcookie** [comment]
> Garnet
> Rules. Rules. Try to be proffesional

got it
oh i gotta go cya

**Comment by LankyBox01** [comment]
Byee and please stop copy-pasting lol

**Comment by LankyBox01** [comment]
Garnet cya

**Comment by garnetluvcookie** [comment]
ok

**Comment by garnetluvcookie** [comment]
ok i just read the whole conversation and i'm cracking up that you called me a specialist or did you

**Comment by LankyBox01** [comment]
Well youre great at making rules.

**Comment by LankyBox01** [comment]
Go ahead and make some rules up now!

**Comment by garnetluvcookie** [comment]
i'll do it after school i'm on a zoom now

**Comment by LankyBox01** [comment]
Kkkkkkk

**Comment by Readtt** [comment]
Same, im in class :p

**Comment by themagiclavalamp** [comment]
can u invite me to the organizaton?

**Comment by LankyBox01** [comment]
@themagiclavalamp done. Check your email

**Comment by garnetluvcookie** [comment]
ok, here's a draft, feel free to revise it:

>TOU

1: User Agreement

1.1: By using the PigeonVideo service, you agree to our Privacy Policy and these Terms of Use (collectively “Terms”). If you do not agree to the Terms, you should not use our service.

1.2: We value your privacy. When you use the Service, your personal information will not be sold or shown to anyone without your consent.

1.3: These Terms will be updated from time to time. Anytime the Terms get updated, you agree to the new Terms, and we advise you to re-read the Terms.


2: Accounts

2.1: In order to access some of the features of PigeonVideo, you will need to make an account. Creating one is optional, but making one is required for using some features of the Service like uploading videos, and commenting. When creating an account, you will need to supply information like your age, and e-mail address.

2.2: You and only you are responsible for keeping your password safe. Any activity on your account is only your responsibility, even if the person is not you.

2.3: PigeonVideo is a site for children. Please keep our guidelines in mind when making and sharing videos that

a. Contain an abundance of blood and/or violence

b. Contain content not appropriate for young children

c. Contain “swear” words

Sharing videos with these types of content in them will be taken down and a strike given to your account. 

2.4: When creating an account, you agree to the fact that your account may be banned or terminated if you repeatedly break our Guidelines of Terms.

2.5: You must be over the age of 13 or have consent from your parent or guardian to make an account.


3: Rules of Usage

3.1: The Developers support free speech on the service. However, you may not use the Service in any way that

a. Promotes violence or hatred against any user or group,

b. Intimidates, threatens, or harasses anyone; whether they are a PigeonVideo user or not,

c. Has foul or derogatory language,

d. Explains how to obtain illegal items or commit crimes

3.2: Please abide by our Guidelines, or a strike will be given to your account.
 
3.3: If your account is banned, DO NOT USE A NEW ACCOUNT OR AN OLD ACCOUNT. This will result in an IP ban. 

3.4: If you have concerns with the service, please contact a developer. We do not have a help email yet.

**Comment by garnetluvcookie** [comment]
question: are we doing this on glitch or github? i see things mentioning migrating to glitch but we're here.

**Comment by themagiclavalamp** [comment]
@LankyBox01 why did you yell at me :(

**Comment by LankyBox01** [comment]
I didn't yell at you.
Maybe you misinterpreted my comment bc you cannot see my facial expression

**Comment by LankyBox01** [comment]
> question: are we doing this on glitch or github? i see things mentioning migrating to glitch but we're here.

We are building the base on github.
And after finishing up the website, we migrate to glitch

**Comment by LankyBox01** [comment]
So, what are we going to do now?

**Comment by aboutDavid** [comment]
https://github.com/PigeonVideo/PigeonVideo.github.io/commit/1576e64c089a469c5b17f998ed1e59891bf8193c
Confusion? What happened?

**Comment by aboutDavid** [comment]
@LankyBox01 What happened to themagiclavalamp?

**Comment by LankyBox01** [comment]
Sorry, but i cannot gossip.
